In [1]:
# IMPORTS 
import pandas as pd

In [2]:
# load in data
df = pd.read_csv("medicare_drug_spending.csv")
df.shape

(14309, 46)

In [32]:
id_vars = ['Brnd_Name', 'Gnrc_Name', 'Tot_Mftr', 'Mftr_Name']

# use wide_to_long to reshape
df_long = pd.wide_to_long(
    df,
    stubnames=[
        'Avg_Spnd_Per_Bene',
        'Avg_Spnd_Per_Clm',
        'Avg_Spnd_Per_Dsg_Unt_Wghtd',
        'Outlier_Flag',
        'Tot_Benes',
        'Tot_Clms',
        'Tot_Dsg_Unts',
        'Tot_Spndng'
    ],
    i=id_vars,          # columns that identify unique rows
    j='Year',           # new column name for year
    sep='_',            # separator between stub and year
    suffix='\d{4}'      # pattern for years
).reset_index()

<>:19: SyntaxWarning: invalid escape sequence '\d'
<>:19: SyntaxWarning: invalid escape sequence '\d'
/var/folders/5b/6lvktnb96955q0486jnqvwf80000gn/T/ipykernel_31776/4057452185.py:19: SyntaxWarning: invalid escape sequence '\d'
  suffix='\d{4}'      # pattern for years

In [33]:
# sanity check between conversions 
drug_name = 'Pen Needle, Diabetic'
df[df['Gnrc_Name'] == drug_name]

,Brnd_Name,Gnrc_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2019,Tot_Dsg_Unts_2019,Tot_Clms_2019,Tot_Benes_2019,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,Avg_Spnd_Per_Clm_2019,...,Tot_Spndng_2023,Tot_Dsg_Unts_2023,Tot_Clms_2023,Tot_Benes_2023,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,Avg_Spnd_Per_Clm_2023,Avg_Spnd_Per_Bene_2023,Outlier_Flag_2023,Chg_Avg_Spnd_Per_Dsg_Unt_22_23,CAGR_Avg_Spnd_Per_Dsg_Unt_19_23
0,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Overall,139201.68,642471.0,5392.0,1878.0,0.216788,25.816335,...,44355.04,195672.0,1613,699.0,0.227162,27.498475,63.454993,0.0,0.005702,0.011754
1,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Owen Mumford Us,139201.68,642471.0,5392.0,1878.0,0.216788,25.816335,...,44355.04,195672.0,1613,699.0,0.227162,27.498475,63.454993,0.0,0.005702,0.011754
2,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Overall,343031.42,1830596.0,14581.0,5319.0,0.187389,23.525919,...,97951.18,406617.0,3269,1267.0,0.240932,29.963652,77.309534,0.0,0.022165,0.064848
3,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Owen Mumford Us,343031.42,1830596.0,14581.0,5319.0,0.187389,23.525919,...,97951.18,406617.0,3269,1267.0,0.240932,29.963652,77.309534,0.0,0.022165,0.064848
270,Advocate Pen Needle,"Pen Needle, Diabetic",1,Overall,176740.05,297000.0,2021.0,1177.0,0.595084,87.451781,...,210908.62,284560.0,1803,809.0,0.741175,116.976495,260.702868,0.0,0.064974,0.056417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13361,Unifine Pentips Plus,"Pen Needle, Diabetic",1,Aurora Health.,2614.99,11030.0,102.0,54.0,0.239101,25.637157,...,1734.49,5400.0,41,17.0,0.321008,42.304634,102.028824,1.0,0.049912,0.076425
13362,Unifine Pentips Plus Maxflow,"Pen Needle, Diabetic",1,Overall,NaN,NaN,NaN,NaN,NaN,NaN,...,2312.92,7100.0,59,38.0,0.325763,39.202034,60.866316,0.0,0.032940,0.032940
13363,Unifine Pentips Plus Maxflow,"Pen Needle, Diabetic",1,Owen Mumford Us,NaN,NaN,NaN,NaN,NaN,NaN,...,2312.92,7100.0,59,38.0,0.325763,39.202034,60.866316,0.0,0.032940,0.032940
13366,Unifine Ultra Pen Needle,"Pen Needle, Diabetic",1,Overall,NaN,NaN,NaN,NaN,NaN,NaN,...,426187.11,687994.0,5207,2527.0,0.619455,81.848878,168.653387,0.0,-0.078989,-0.078989
13367,Unifine Ultra Pen Needle,"Pen Needle, Diabetic",1,Owen Mumford Us,NaN,NaN,NaN,NaN,NaN,NaN,...,426187.11,687994.0,5207,2527.0,0.619455,81.848878,168.653387,0.0,-0.078989,-0.078989

In [34]:
# --- 5 total years 
147*5
df[df['Gnrc_Name'] == drug_name].head(10)

,Brnd_Name,Gnrc_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2019,Tot_Dsg_Unts_2019,Tot_Clms_2019,Tot_Benes_2019,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,Avg_Spnd_Per_Clm_2019,...,Tot_Spndng_2023,Tot_Dsg_Unts_2023,Tot_Clms_2023,Tot_Benes_2023,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,Avg_Spnd_Per_Clm_2023,Avg_Spnd_Per_Bene_2023,Outlier_Flag_2023,Chg_Avg_Spnd_Per_Dsg_Unt_22_23,CAGR_Avg_Spnd_Per_Dsg_Unt_19_23
0,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Overall,139201.68,642471.000,5392.0,1878.0,0.216788,25.816335,...,44355.04,195672.000,1613,699.0,0.227162,27.498475,63.454993,0.0,0.005702,0.011754
1,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Owen Mumford Us,139201.68,642471.000,5392.0,1878.0,0.216788,25.816335,...,44355.04,195672.000,1613,699.0,0.227162,27.498475,63.454993,0.0,0.005702,0.011754
2,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Overall,343031.42,1830596.000,14581.0,5319.0,0.187389,23.525919,...,97951.18,406617.000,3269,1267.0,0.240932,29.963652,77.309534,0.0,0.022165,0.064848
3,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Owen Mumford Us,343031.42,1830596.000,14581.0,5319.0,0.187389,23.525919,...,97951.18,406617.000,3269,1267.0,0.240932,29.963652,77.309534,0.0,0.022165,0.064848
270,Advocate Pen Needle,"Pen Needle, Diabetic",1,Overall,176740.05,297000.000,2021.0,1177.0,0.595084,87.451781,...,210908.62,284560.000,1803,809.0,0.741175,116.976495,260.702868,0.0,0.064974,0.056417
271,Advocate Pen Needle,"Pen Needle, Diabetic",1,Diabetic Supply,176740.05,297000.000,2021.0,1177.0,0.595084,87.451781,...,210908.62,284560.000,1803,809.0,0.741175,116.976495,260.702868,0.0,0.064974,0.056417
272,Advocate Pen Needles,"Pen Needle, Diabetic",1,Overall,1659681.10,3066628.666,26142.0,9128.0,0.541237,63.487151,...,1797604.62,2528681.999,19094,7160.0,0.710469,94.144999,251.062098,0.0,0.029188,0.070383
273,Advocate Pen Needles,"Pen Needle, Diabetic",1,Diabetic Supply,1659681.10,3066628.666,26142.0,9128.0,0.541237,63.487151,...,1797604.62,2528681.999,19094,7160.0,0.710469,94.144999,251.062098,0.0,0.029188,0.070383
2036,Carefine Pen Needle,"Pen Needle, Diabetic",1,Overall,120651.95,350263.000,2707.0,1263.0,0.343658,44.570355,...,73563.08,201533.000,1379,639.0,0.362643,53.345236,115.122191,0.0,0.029801,0.013533
2037,Carefine Pen Needle,"Pen Needle, Diabetic",1,Facet Technolog,120651.95,350263.000,2707.0,1263.0,0.343658,44.570355,...,73563.08,201533.000,1379,639.0,0.362643,53.345236,115.122191,0.0,0.029801,0.013533

In [25]:
df_long[(df_long['Gnrc_Name'] == drug_name) & (df_long['Year'] == 2019)].head(10)

,Brnd_Name,Gnrc_Name,Tot_Mftr,Mftr_Name,Year,CAGR_Avg_Spnd_Per_Dsg_Unt_19_23,Chg_Avg_Spnd_Per_Dsg_Unt_22_23,Tot_Spndng,Tot_Dsg_Unts,Tot_Clms,Tot_Benes,Avg_Spnd_Per_Dsg_Unt_Wghtd,Avg_Spnd_Per_Clm,Avg_Spnd_Per_Bene,Outlier_Flag
0,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Overall,2019,0.011754,0.005702,139201.68,642471.000,5392.0,1878.0,0.216788,25.816335,74.122300,0.0
5,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Owen Mumford Us,2019,0.011754,0.005702,139201.68,642471.000,5392.0,1878.0,0.216788,25.816335,74.122300,0.0
10,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Overall,2019,0.064848,0.022165,343031.42,1830596.000,14581.0,5319.0,0.187389,23.525919,64.491713,0.0
15,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Owen Mumford Us,2019,0.064848,0.022165,343031.42,1830596.000,14581.0,5319.0,0.187389,23.525919,64.491713,0.0
1350,Advocate Pen Needle,"Pen Needle, Diabetic",1,Overall,2019,0.056417,0.064974,176740.05,297000.000,2021.0,1177.0,0.595084,87.451781,150.161470,0.0
1355,Advocate Pen Needle,"Pen Needle, Diabetic",1,Diabetic Supply,2019,0.056417,0.064974,176740.05,297000.000,2021.0,1177.0,0.595084,87.451781,150.161470,0.0
1360,Advocate Pen Needles,"Pen Needle, Diabetic",1,Overall,2019,0.070383,0.029188,1659681.10,3066628.666,26142.0,9128.0,0.541237,63.487151,181.823083,0.0
1365,Advocate Pen Needles,"Pen Needle, Diabetic",1,Diabetic Supply,2019,0.070383,0.029188,1659681.10,3066628.666,26142.0,9128.0,0.541237,63.487151,181.823083,0.0
10180,Carefine Pen Needle,"Pen Needle, Diabetic",1,Overall,2019,0.013533,0.029801,120651.95,350263.000,2707.0,1263.0,0.343658,44.570355,95.528068,0.0
10185,Carefine Pen Needle,"Pen Needle, Diabetic",1,Facet Technolog,2019,0.013533,0.029801,120651.95,350263.000,2707.0,1263.0,0.343658,44.570355,95.528068,0.0

In [40]:
# sanity checks
df_long[(df_long['Gnrc_Name'] == drug_name) & (df_long['Year'] == 2019) & (df_long['Mftr_Name'] == 'Overall')]['Tot_Spndng']

0        1.392017e+05
10       3.430314e+05
1350     1.767400e+05
1360     1.659681e+06
10180    1.206519e+05
10200    2.461780e+03
12920    1.312525e+05
14735    3.263149e+07
14760             NaN
20650             NaN
20660    4.618219e+06
21160    9.620098e+06
21170    1.024082e+07
21210    2.450771e+05
21330    3.597559e+06
21800             NaN
29925    1.447650e+03
29935    2.110901e+05
32115    5.239886e+05
32535    6.333830e+03
32825    1.797650e+05
32835    4.382883e+04
37905    1.265350e+05
39555    9.516200e+02
42655             NaN
43010             NaN
43020    5.052526e+04
44925    2.976946e+06
46615    1.552626e+07
46635    4.513672e+06
46815    2.691153e+06
50735    7.418020e+06
50810    9.297189e+06
51050    3.612312e+05
54010    1.627985e+06
55015             NaN
56050             NaN
61090    3.510572e+05
61170    3.712425e+06
61190    9.219620e+03
62315    1.113074e+06
65960             NaN
66000             NaN
66050    5.510042e+06
66440    1.418125e+07
66500    4.706700e+02
66580             NaN
66590    2.179890e+03
66600    4.473757e+06
66610    5.745417e+07
66620    1.024985e+08
66635    7.302482e+06
66645    5.635762e+07
66655    5.304151e+04
66725    4.554405e+06
66755    7.370866e+06
66770             NaN
66780    2.582432e+06
66810             NaN
66830             NaN
Name: Tot_Spndng, dtype: float64

In [41]:
df_long.isna().sum()

Brnd_Name                              0
Gnrc_Name                              0
Tot_Mftr                               0
Mftr_Name                              0
Year                                   0
CAGR_Avg_Spnd_Per_Dsg_Unt_19_23     5805
Chg_Avg_Spnd_Per_Dsg_Unt_22_23      6630
Avg_Spnd_Per_Bene                  13026
Avg_Spnd_Per_Clm                   11067
Avg_Spnd_Per_Dsg_Unt_Wghtd         11067
Outlier_Flag                       11099
Tot_Benes                          12809
Tot_Clms                           11067
Tot_Dsg_Unts                       11067
Tot_Spndng                         11067
dtype: int64

In [42]:
df_long.shape

(71545, 15)

In [45]:
13026 / df_long.shape[0]

0.1820672304144245